"""Serializable output schema for alignment and derived audio artifacts."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any


SCHEMA_VERSION = 1


@dataclass(frozen=True)
class ArtifactPaths:
    """Paths generated by preparation, relative to the song directory."""

    alignment: str = "alignment.json"
    preprocessing: str = "preprocessing.json"
    vocals: str | None = "stems/vocals.flac"
    instrumental: str | None = "stems/instrumental.flac"


@dataclass
class AlignmentLine:
    source_index: int
    text: str
    reading: str = ""
    romaji: str = ""
    start_ms: int = 0
    end_ms: int = 0
    status: str = "unresolved"
    method: str = ""
    confidence: float | None = None
    mora: list[dict[str, Any]] = field(default_factory=list)
    surface_spans: list[dict[str, Any]] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    def validate(self) -> None:
        if self.start_ms < 0 or self.end_ms < self.start_ms:
            raise ValueError("line times must satisfy 0 <= start_ms <= end_ms")
        previous = self.start_ms
        for item in self.mora:
            start, end = int(item["start_ms"]), int(item["end_ms"])
            if start < self.start_ms or end < start or end > self.end_ms:
                raise ValueError("mora time must be inside its line interval")
            if start < previous:
                raise ValueError("mora times must be monotonic")
            previous = start


@dataclass
class AlignmentArtifact:
    """Top-level, versioned result consumed by downstream renderers."""

    song: dict[str, Any]
    inputs: dict[str, Any]
    timing: dict[str, Any]
    lines: list[AlignmentLine]
    stages: dict[str, Any]
    models: dict[str, Any]
    artifacts: ArtifactPaths = field(default_factory=ArtifactPaths)
    schema_version: int = SCHEMA_VERSION

    def validate(self) -> None:
        if self.schema_version != SCHEMA_VERSION:
            raise ValueError(f"unsupported alignment schema {self.schema_version}")
        for line in self.lines:
            line.validate()

    def to_dict(self) -> dict[str, Any]:
        self.validate()
        value = asdict(self)
        value["artifacts"] = asdict(self.artifacts)
        return value

    @classmethod
    def from_dict(cls, value: dict[str, Any]) -> "AlignmentArtifact":
        lines = [AlignmentLine(**line) for line in value.get("lines", [])]
        artifact = cls(
            schema_version=int(value.get("schema_version", 0)),
            song=dict(value.get("song") or {}),
            inputs=dict(value.get("inputs") or {}),
            timing=dict(value.get("timing") or {}),
            lines=lines,
            stages=dict(value.get("stages") or {}),
            models=dict(value.get("models") or {}),
            artifacts=ArtifactPaths(**dict(value.get("artifacts") or {})),
        )
        artifact.validate()
        return artifact
