"""Serializable output schema for alignment and derived audio artifacts."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any


SCHEMA_VERSION = 1
_LINE_STATUSES = {"non_sung", "unresolved", "interpolation", "ctc", "fallback"}
_ALIGNMENT_STATUSES = {"ctc", "fallback", "activity", "interpolation", "unresolved", None}


@dataclass(frozen=True)
class ArtifactPaths:
    """Paths generated by preparation, relative to the song directory."""

    alignment: str = "alignment.json"
    preprocessing: str = "preprocessing.json"
    vocals: str | None = "stems/vocals.mp3"
    instrumental: str | None = "stems/instrumental.mp3"


@dataclass
class AlignmentLine:
    source_index: int
    text: str
    reading: str = ""
    romaji: str = ""
    start_ms: int = 0
    end_ms: int = 0
    original_start_ms: int | None = None
    original_end_ms: int | None = None
    singing_end_ms: int | None = None
    singing_start_ms: int | None = None
    activity_confidence: float | None = None
    status: str = "unresolved"
    method: str = ""
    confidence: float | None = None
    ctc_score: float | None = None
    coverage: float | None = None
    alignment_status: str | None = None
    timing_source: str = "line_interpolation"
    tokens: list[dict[str, Any]] = field(default_factory=list)
    mora: list[dict[str, Any]] = field(default_factory=list)
    surface_spans: list[dict[str, Any]] = field(default_factory=list)
    # Final renderer contract.  These units are the only character timing
    # values a consumer should use; tokens/mora remain diagnostic/model data.
    display_units: list[dict[str, Any]] = field(default_factory=list)
    ctc_window: dict[str, Any] = field(default_factory=dict)
    warnings: list[str] = field(default_factory=list)

    def validate(self) -> None:
        if self.start_ms < 0 or self.end_ms < self.start_ms:
            raise ValueError("line times must satisfy 0 <= start_ms <= end_ms")
        if self.status not in _LINE_STATUSES:
            raise ValueError(f"unsupported line status: {self.status}")
        if self.alignment_status not in _ALIGNMENT_STATUSES:
            raise ValueError(f"unsupported alignment status: {self.alignment_status}")
        if self.timing_source not in {"ctc", "ctc_rescaled", "activity_interpolation", "line_interpolation"}:
            raise ValueError(f"unsupported timing source: {self.timing_source}")
        if self.coverage is not None and not 0.0 <= float(self.coverage) <= 1.0:
            raise ValueError("coverage must be between 0 and 1")
        if self.singing_end_ms is not None and not self.start_ms <= int(self.singing_end_ms) <= self.end_ms:
            raise ValueError("singing_end_ms must be inside its line interval")
        if self.singing_start_ms is not None and not self.start_ms <= int(self.singing_start_ms) <= self.end_ms:
            raise ValueError("singing_start_ms must be inside its line interval")
        if self.singing_start_ms is not None and self.singing_end_ms is not None and self.singing_start_ms > self.singing_end_ms:
            raise ValueError("singing_start_ms must not exceed singing_end_ms")
        if self.activity_confidence is not None and not 0.0 <= float(self.activity_confidence) <= 1.0:
            raise ValueError("activity_confidence must be between 0 and 1")
        if self.confidence is not None and not 0.0 <= float(self.confidence) <= 1.0:
            raise ValueError("confidence must be between 0 and 1")
        previous = self.start_ms
        for item in self.mora:
            start, end = int(item["start_ms"]), int(item["end_ms"])
            if start < self.start_ms or end < start or end > self.end_ms:
                raise ValueError("mora time must be inside its line interval")
            if start < previous:
                raise ValueError("mora times must be monotonic")
            previous = start
        for item in self.tokens:
            start, end = int(item["start_ms"]), int(item["end_ms"])
            if start < self.start_ms or end < start or end > self.end_ms:
                raise ValueError("CTC token time must be inside its line interval")
        previous = self.start_ms
        for item in self.display_units:
            start, end = int(item["start_ms"]), int(item["end_ms"])
            if start < self.start_ms or end < start or end > self.end_ms:
                raise ValueError("display unit time must be inside its line interval")
            if start < previous:
                raise ValueError("display unit times must be monotonic")
            previous = start


@dataclass
class AlignmentArtifact:
    """Top-level, versioned result consumed by downstream renderers."""

    song: dict[str, Any]
    inputs: dict[str, Any]
    timing: dict[str, Any]
    lines: list[AlignmentLine]
    stages: dict[str, Any]
    models: dict[str, Any]
    artifacts: ArtifactPaths = field(default_factory=ArtifactPaths)
    schema_version: int = SCHEMA_VERSION

    def validate(self) -> None:
        if self.schema_version != SCHEMA_VERSION:
            raise ValueError(f"unsupported alignment schema {self.schema_version}")
        for line in self.lines:
            line.validate()

    def to_dict(self) -> dict[str, Any]:
        self.validate()
        value = asdict(self)
        value["artifacts"] = asdict(self.artifacts)
        return value

    @classmethod
    def from_dict(cls, value: dict[str, Any]) -> "AlignmentArtifact":
        lines = [AlignmentLine(**line) for line in value.get("lines", [])]
        artifact = cls(
            schema_version=int(value.get("schema_version", 0)),
            song=dict(value.get("song") or {}),
            inputs=dict(value.get("inputs") or {}),
            timing=dict(value.get("timing") or {}),
            lines=lines,
            stages=dict(value.get("stages") or {}),
            models=dict(value.get("models") or {}),
            artifacts=ArtifactPaths(**dict(value.get("artifacts") or {})),
        )
        artifact.validate()
        return artifact
